version: '3.1'

services:
  jrtb-db-dev:
    image: mysql
    restart: always
    container_name: dev-jrtb-db
    ports:
      - '3307:3306'
    expose:
      - '3307'
    env_file:
      - ./jrtb-db-dev.env