version: '3.1'

services:
  nptb-db:
    image: mysql:5.7
    restart: always
    env_file:
      - C:\Users\Дмитрий\IdeaProjects\nasa-photo-telegrambot\nasatb-db-dev.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'