version: '3.1'

services:
  nptb:
    depends_on:
      - nptb-db
    build:
      context: .
    env_file:
     - nasatb-db-prod.env
    restart: always
  nptb-db:
    image: postgres
    restart: always
    env_file:
      - nasatb-db-prod.env
    ports:
      - '5433:5433'
